apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/alibaba-cloud-loadbalancer-spec: slb.s1.small
  name: aiops-slb
  namespace: {{ .Values.common.namespace}}
spec:
  ports:
    - name: slb
      port: 80
      protocol: TCP
      targetPort: 9080
  selector:
    app: insights-client
  sessionAffinity: None
  type: LoadBalancer