apiVersion: v1
kind: Service
metadata:
  name: insights-mysql-connection-service
  namespace: {{ .Values.common.namespace}}
spec:
  ports:
    - name: insights-mysql-connection-service
      port: 9190
      protocol: TCP
      targetPort: 9190
  type: ClusterIP
  selector:
    app: insights-mysql-connection