apiVersion: v1
kind: Service
metadata:
  name: insights-http-service-1
  namespace: {{ .Values.common.namespace}}
spec:
  ports:
    - name: insights-http-service-1
      port: 9190
      protocol: TCP
      targetPort: 9190
  type: ClusterIP
  selector:
    app: insights-http-server-1