{{ if .Values.goapp.enable }}
apiVersion: v1
kind: Service
metadata:
  name: gin-c
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: 20003
      protocol: TCP
      targetPort: 20003
  selector:
    app: gin-c
  type: ClusterIP
 {{ end }}