apiVersion: v1
kind: Service
metadata:
  name: spring-cloud-d
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: 20004
      protocol: TCP
      targetPort: 20004
  selector:
    app: spring-cloud-d
  type: ClusterIP
