# 镜像地址的前缀
registry: registry.cn-hangzhou.aliyuncs.com/mse-governance-demo/

images:
  version: 3.1.0

# 是否启动zuul、springcloud网关
gateway:
  zuul: false
  springcloud: true
  mse:
    ingress: false

goapp:
  enable: false

mse:
  namespace: default

nacos:
  # Nacos地址
  host: nacos-server
  # 注册到Nacos的命名空间id
  namespace: public

middleware:
  mq:
    address: mqnamesrv:9876

autoscaling: false

resources:
  enable: true
  request:
    cpu: 1
    memory: 2Gi
  limit:
    cpu: 1
    memory: 2Gi
