{{ if .Values.autoscaling }}
apiVersion: autoscaling.alibabacloud.com/v1beta1
kind: CronHorizontalPodAutoscaler
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: cronhpa-deployment-spring-cloud-b
spec:
  jobs:
  - name: 扩容
    schedule: 0 0/6 * * * *
    targetSize: 6
  - name: 缩容
    schedule: 0 5/6 * * * *
    targetSize: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: spring-cloud-b
{{ end }}
