apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-cloud-zuul
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-cloud-zuul
  template:
    metadata:
      labels:
        msePilotAutoEnable: "on"
        msePilotCreateAppName: "spring-cloud-zuul"
        mseNamespace: "{{ .Values.mse.namespace }}"
        app: spring-cloud-zuul
    spec:
      containers:
        - image: "{{ .Values.registry }}spring-cloud-zuul:1.2.0"
          imagePullPolicy: Always
          env:
            - name: nacos.host
              value: "{{ .Values.nacos.host }}"
            - name: nacos.namespace
              value: "{{ .Values.nacos.namespace }}"
            {{ if .Values.MSE_DEBUG_HOST }}
            - name: MSE_DEBUG_HOST
              value: {{ .Values.MSE_DEBUG_HOST }}
            {{ end }}
          name: "spring-cloud-zuul"
          resources:
            requests:
              cpu: 1
              memory: 2Gi
            limits:
              cpu: 1
              memory: 2Gi
          ports:
            - containerPort: 20000
      hostAliases:
        {{ toYaml .Values.hostAliases | nindent 8 }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                topologyKey: failure-domain.beta.kubernetes.io/zone
              weight: 50
            - podAffinityTerm:
                topologyKey: kubernetes.io/hostname
              weight: 100
