{{ if .Values.goapp.enable }}
apiVersion: v1
kind: Service
metadata:
  name: go-app
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: go-app
  type: ClusterIP
 {{ end }}