apiVersion: v1
kind: Service
metadata:
  name: spring-cloud-b
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: 20002
      protocol: TCP
      targetPort: 20002
  selector:
    app: spring-cloud-b
  type: ClusterIP
