apiVersion: v1
kind: Service
metadata:
  name: go-b-service
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: port-1
      port: 50052
      protocol: TCP
      targetPort: 50052
  selector:
    app: b-server
  type: ClusterIP
