apiVersion: v1
kind: Service
metadata:
  name: go-c-service
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: port-1
      port: 50053
      protocol: TCP
      targetPort: 50053
  selector:
    app: c-server
  type: ClusterIP
